export const allCardColors = [
  {
    backgroundColor: '#070707',
    textColor: '#ffffff',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#553555',
    textColor: '#ffffff',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#755b69',
    textColor: '#ffffff',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#96c5b0',
    textColor: '#000000',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#4df1d2',
    textColor: '#000000',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#86e7b8',
    textColor: '#000000',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#f2f5de',
    textColor: '#000000',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#d0ffb7',
    textColor: '#000000',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#fde8e9',
    textColor: '#000000',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#e3bac6',
    textColor: '#000000',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#bc9ec1',
    textColor: '#000000',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#596475',
    textColor: '#ffffff',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#1f2232',
    textColor: '#ffffff',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#214f4b',
    textColor: '#ffffff',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#e9d985',
    textColor: '#000000',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#b2bd7e',
    textColor: '#000000',
    buttonColor: '#000000',
    buttonTextColor: '#ffffff',
    tagBackgroundColor: '#ffffff',
    tagTextColor: '#000000',
  },
  {
    backgroundColor: '#749c75',
    textColor: '#ffffff',
    buttonColor: '#ffffff',
    buttonTextColor: '#000000',
    tagBackgroundColor: '#000000',
    tagTextColor: '#ffffff',
  },
  {
    backgroundColor: '#6a5d7b',
    textColor: '#ffffff',
    buttonColor: '#ffffff',
    buttonTextColor: '#000000',
    tagBackgroundColor: '#000000',
    tagTextColor: '#ffffff',
  },
  {
    backgroundColor: '#5d4a66',
    textColor: '#ffffff',
    buttonColor: '#ffffff',
    buttonTextColor: '#000000',
    tagBackgroundColor: '#000000',
    tagTextColor: '#ffffff',
  },
];

export const pickRandomColor = () => {
  const randomIndex = Math.floor(Math.random() * allCardColors.length);
  return allCardColors[randomIndex];
};
